"""empty message

Revision ID: 3a0bbadf2255
Revises: 1bef3b2be722
Create Date: 2025-07-28 23:05:44.355504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a0bbadf2255'
down_revision = '1bef3b2be722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('petfinder_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_column('petfinder_id')

    # ### end Alembic commands ###
