"""empty message

Revision ID: 413cc834ea78
Revises: bf16dd515997
Create Date: 2025-07-02 01:03:44.941144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413cc834ea78'
down_revision = 'bf16dd515997'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
