"""empty message

Revision ID: 4488dac8f44a
Revises: 413cc834ea78
Create Date: 2025-07-04 01:23:09.640932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4488dac8f44a'
down_revision = '413cc834ea78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint('message_message_from_key', type_='unique')
        batch_op.drop_constraint('message_message_to_key', type_='unique')
        batch_op.create_foreign_key(None, 'user', ['message_to'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['message_from'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('message_message_to_key', ['message_to'])
        batch_op.create_unique_constraint('message_message_from_key', ['message_from'])

    # ### end Alembic commands ###
