"""empty message

Revision ID: 9c5ecf1604e3
Revises: 5902e417ff68
Create Date: 2025-07-21 23:50:59.020944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c5ecf1604e3'
down_revision = '5902e417ff68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('petfinder_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_column('petfinder_id')

    # ### end Alembic commands ###
